---
# Default variables for elasticsearch role

# 集群配置
cluster_name: eslog-cluster

# Elasticsearch 配置
es_heap_size: 8192m
es_http_port: 9200
es_transport_port: 9300
es_memory_limit: 16g
es_snapshot_repo_path: /opt/eslog-cluster/es-snapshots
elk_image: sebp/elk:651

# 部署目录
deploy_dir: /opt/eslog-cluster

# 时区
timezone: Asia/Shanghai

# 系统配置
vm_max_map_count: 262144
vm_swappiness: 0
nofile_soft: 655360
nofile_hard: 655360
