---
# Default variables for nginx role
nginx_listen_port: 80
es_domain: es.example.com
kibana_domain: kibana.example.com

# Will be auto-detected from OS, can be overridden
nginx_conf_d_path: "/etc/nginx/conf.d"
nginx_default_conf_path: "/etc/nginx/conf.d/default.conf"
